spring:
  profiles:
    active: dev
---
server:
  port: 8001 
spring:
   profiles: dev
   application:
     name: microservicecloud-config-dept-client
   datasource:
       driver-class-name: com.mysql.jdbc.Driver             
       url: jdbc:mysql://localhost:3306/cloudDB01            
       username: root
       password: root
       type: com.alibaba.druid.pool.DruidDataSource           
mybatis:
  #类别名
  type-aliases-package: com.sxt.pojo
logging:
  level: 
   #输出sql语句
    com.sxt.mapper: debug 
eureka:
   client: 
      service-url:
         defaultZone: http://127.0.0.1:7001/eureka/
   instance:
      instance-id: dept-8001.com
      prefer-ip-address: true
---
server:
  port: 8002
spring:
   profiles: test
   application:
     name: microservicecloud-config-dept-client
   datasource:
       driver-class-name: com.mysql.jdbc.Driver            
       url: jdbc:mysql://localhost:3306/cloudDB02             
       username: root
       password: root
       type: com.alibaba.druid.pool.DruidDataSource           
mybatis:
  #类别名
  type-aliases-package: com.sxt.pojo
logging:
  level: 
   #输出sql语句
    com.sxt.mapper: debug      
eureka:
   client: 
      service-url:
         defaultZone: http://127.0.0.1:7001/eureka/
   instance:
      instance-id: dept-8002.com
      prefer-ip-address: true 